version: '3.7'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'